### ISSUE TITLE
Issue of MainPage

### ISSUE THREAD

**Issue by dingf3ng** [dingf3ng/spoplusplusfy#14]
I wish to let the containers on MainPage display 'album_gold.png' if the loading process throws exception, but not success yet.

**Comment by kaoxi998533** [comment]
noted. will try fix

**Comment by kaoxi998533** [comment]
Container(
                  width: 170,
                  height: 170,
                  decoration: BoxDecoration(
                    border: Border.all(
                      color: goldColour,
                      width: 3,
                    ),
                    color: goldColour,
                    borderRadius: BorderRadius.circular(30),
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(30),
                    child: FadeInImage(
                      image: NetworkImage(playlists[index].getCoverPath(), scale: 0.1),
                      placeholder: AssetImage('assets/images/playlist_cover.jpg'),
                      imageErrorBuilder: (context, obj, st) {
                        return Image.asset('assets/images/pf.jpg');
                      }
                    ),
                  ),
                ),
              ],
            ),
            
            This solves the issue. Decoration image is replaced with a child using cliprrect

**Comment by kaoxi998533** [comment]
solved, thus close
